apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobName }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": {{ .Values.helmHook }}
spec:
  activeDeadlineSeconds: {{ int .Values.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ int .Values.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: {{ .Values.jobName }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.commonPodAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
        {{- with .Values.commonPodAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      {{- end }}
    spec:
      containers:
        - name: topic-creator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: configs
              mountPath: /opt/kafka
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: configs
          configMap:
            name: {{ .Values.jobName }}
  backoffLimit: 100
