{{- if .Values.workloads }}
{{- $jobName := default (printf "kstreams-app-version-%s" .Release.Name) .Values.jobName }}
{{- $configMapName := default (printf "kstreams-app-version-%s" .Release.Name) .Values.configMapName }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    app: {{ $jobName }}
    release: {{ .Release.Name }}
  name: {{ $jobName }}
spec:
  activeDeadlineSeconds: {{ int .Values.activeDeadlineSeconds }}
  backoffLimit: {{ int .Values.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ $jobName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: kstreams-app-version
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tagOverride }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WAIT_SECONDS
              value: {{ int .Values.waitSeconds | quote }}
            - name: WORKLOADS
              value: "{{ range $workload := .Values.workloads }}{{ $workload.name }},{{ $workload.type }},{{ $workload.container }};{{ end }}"
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ $configMapName }}
              mountPath: /opt/versions
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      serviceAccountName: {{ $jobName }}
      volumes:
        - name: {{ $configMapName }}
          configMap:
            name: {{ $configMapName }}
  ttlSecondsAfterFinished: {{ int .Values.ttlSecondsAfterFinished }}
{{- end }}
