{{- if .Values.workloads }}
{{- $jobName := default (printf "kstreams-app-version-%s" .Release.Name) .Values.jobName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    release: {{ $.Release.Name }}
  name: {{ $jobName }}
{{- end }}
