{{- if .Values.workloads }}
{{- $jobName := default (printf "kstreams-app-version-%s" .Release.Name) .Values.jobName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    release: {{ $.Release.Name }}
  name: {{ $jobName }}
{{- end }}
