apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.jobName }}
  annotations:
    "helm.sh/hook": {{ .Values.helmHook }}
  labels:
    release: {{ .Release.Name }}
data:
  topics.json: |-
    {{ toJson .Values.kafka }}
