apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.jobName }}
  annotations:
    "helm.sh/hook": {{ .Values.helmHook }}
  labels:
    release: {{ .Release.Name }}
data:
  config.yaml: |-
    {{- toYaml .Values.kafka | nindent 4 }}
