# Default values for the helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# Note about Namespace
# --------------------
# It is deliberately left out here and using the helm -n or --namespace flag you can deploy your resources to the same
# namespace as the release. If you leave it out, your resources will be deployed to the default namespace.
# Also, not that the namespace you are deploying to should already exist otherwise the helm command will fail.
# You can always specify a different namespace for a resource by setting it directly in it's yaml file or
# making it configurable by defining it in this file.

###########
# Job
###########

image:
  repository: hypertrace/kafka-topic-creator
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

resources: {}

env: []

nodeSelector: {}

affinity: {}

tolerations: {}

securityContext: {}

podLabels: {}

activeDeadlineSeconds: 600

ttlSecondsAfterFinished: 900

kafka:
  address: "bootstrap:9092"
  topics: {}
  # for these keys in minValueOverrideForTopicConfig, we will set for all topics to value here if either not set or when lower is provided
  # ensure provided value for these keys is a 64 bit integer, else job will throw an error
  minValueOverrideForTopicConfig: {}
