name: build and validate
on:
  schedule:
    - cron: 30 2 * * 1
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with:
          args: dockerBuildImages

      - name: Run Trivy vulnerability scanner
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/kafka-topic-creator
          output-mode: github

  validate-helm-charts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
        with:
          chart-path: ./helm/
