name: validate
on:
  schedule:
    - cron: 30 2 * * 1
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-helm-charts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
        with:
          chart-path: ./helm/ -f src/test/resources/values.yaml

  scan-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Determine docker image
        id: docker
        run: |
          echo repository=$(yq e '.image.repository' ./helm/values.yaml) >> $GITHUB_OUTPUT
          echo tag=$(yq e '.image.tag' ./helm/values.yaml) >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker Image
        run: docker pull ${{ steps.docker.outputs.repository }}:${{ steps.docker.outputs.tag }}

      - name: Run Trivy vulnerability scanner for kafka image
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: ${{ steps.docker.outputs.repository }}
          tag: ${{ steps.docker.outputs.tag }}
          output-mode: github
