name: build and validate
on:
  schedule:
    - cron: 30 8 * * 2
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted-x64-small
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup gradle auth
        uses: traceableai/github-actions/gradle-setup@main
        with:
          context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          user: ${{ secrets.ARTIFACTORY_READ_USER }}
          password: ${{ secrets.ARTIFACTORY_READ_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build kafka-topic-creator Image
        uses: docker/build-push-action@v6
        with:
          context: kafka-topic-creator
          cache-from: type=registry,ref=${{ secrets.GCP_CACHE_ARTIFACT_REGISTRY }}/traceable/kafka-topic-creator
          tags: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/traceable/kafka-topic-creator:test
          load: true

      - name: Build kstreams-app-version-checker Image
        uses: docker/build-push-action@v6
        with:
          context: kstreams-app-version-checker
          cache-from: type=registry,ref=${{ secrets.GCP_CACHE_ARTIFACT_REGISTRY }}/traceable/kstreams-app-version-checker
          tags: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/traceable/kstreams-app-version-checker:test
          load: true

      - name: Scan container image
        uses: traceableai/github-actions/container-image-scan@main
        with:
          image: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/traceable/kafka-topic-creator
          tag: test

      - name: Scan kstreams-app-version-checker image
        if: "!cancelled()"
        uses: traceableai/github-actions/container-image-scan@main
        with:
          image: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/traceable/kstreams-app-version-checker
          tag: test

  validate-helm-charts:
    runs-on: self-hosted-x64-small
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
