name: validate
on:
  schedule:
    - cron: 30 2 * * 1
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-helm-charts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
        with:
          chart-path: ./kafka-topic-creator/helm/

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
        with:
          chart-path: ./kstreams-app-version/helm/

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Determine docker image
        id: docker
        run: |
          echo repository=$(yq e '.image.repository' ./kafka-topic-creator/helm/values.yaml) >> $GITHUB_OUTPUT
          echo tag=$(yq e '.image.tag' ./kafka-topic-creator/helm/values.yaml) >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker Image
        run: docker pull ${{ steps.docker.outputs.repository }}:${{ steps.docker.outputs.tag }}

      - name: Build kstreams-app-version image
        uses: docker/build-push-action@v3
        with:
          tags: hypertrace/kstreams-app-version:test
          context: kstreams-app-version
          load: true

      - name: Scan kafka image
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: ${{ steps.docker.outputs.repository }}
          tag: ${{ steps.docker.outputs.tag }}
          output-mode: github
          category: kafka-topic-creator

      - name: Scan kstreams-app-version image
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/kstreams-app-version
          tag: test
          output-mode: github
          category: kstreams-app-version
