name: validate
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  validate-helm-charts:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
        with: 
          chart-path: ./helm/ -f src/test/resources/values.yaml