name: Publish artifacts
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: self-hosted-x64-small
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup gradle auth
        uses: traceableai/github-actions/gradle-setup@main
        with:
          context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          user: ${{ secrets.ARTIFACTORY_READ_USER }}
          password: ${{ secrets.ARTIFACTORY_READ_TOKEN }}

      - name: Determine version
        id: version
        run: echo version=$(./gradlew -q -Prelease :printVersion) >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}

  publish-artifacts:
    runs-on: self-hosted-x64-small
    needs: [ create-release ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup gradle auth
        uses: traceableai/github-actions/gradle-setup@main
        with:
          context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          user: ${{ secrets.ARTIFACTORY_PUBLISH_USER }}
          password: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN }}

      - name: Determine docker tag
        id: tag
        run: echo tag=$(./gradlew -q printDockerImageDefaultTag | head -1) >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish kafka-topic-creator image
        uses: traceableai/github-actions/docker-build-sign-publish@main
        with:
          context: docker
          image: traceable/kafka-topic-creator
          tags: ${{ steps.tag.outputs.tag }}

      - name: Publish kstreams-app-version-checker image
        uses: traceableai/github-actions/docker-build-sign-publish@main
        with:
          context: docker
          image: traceable/kstreams-app-version-checker
          tags: ${{ steps.tag.outputs.tag }}

  publish-charts:
    needs: [ create-release, publish-artifacts ]
    runs-on: self-hosted-x64-small
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and release chart
        uses: traceableai/github-actions/helm-artifactory-publish@main
        with:
          helm-artifactory-user: ${{ secrets.ARTIFACTORY_PUBLISH_USER }}
          helm-artifactory-password: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN }}

  publish-release-notes:
    runs-on: self-hosted-x64-small
    needs: [ create-release ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hypertrace/github-actions/release-notes@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
