name: Publish artifacts
on:
# Will only run when release is published. 
  pull_request:
  release:
    types: 
      - created
  workflow_dispatch:

jobs:
  validate-helm-charts:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main

  publish-helm-charts:
    runs-on: ubuntu-20.04
    if: github.event_name == 'release'
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
   
      - name: package and release charts
        uses: hypertrace/github-actions/helm-gcs-publish@main
        with: 
          helm-gcs-credentials: ${{ secrets.HELM_GCS_CREDENTIALS }}
          helm-gcs-repository: ${{ secrets.HELM_GCS_REPOSITORY }}

